protected_remove_trailing_slash:
  controller: ProtectedBundle:Default:removeTrailingSlash
  path: /{url}
  methods: [GET]
  requirements:
    url: .*/$
protected_not_found:
  controller: ProtectedBundle:Default:notFound
  path: /{url}
  requirements:
    url: .*
