protected_test:
    controller: ProtectedBundle:Default:test
    path: /test/{path}
    defaults: {path: null}
    requirements:
        path: .*

##==secure
_protected_secure:
  prefix: '/%protected.secure.path%'
  resource: '@ProtectedBundle/Resources/config/routing.secure.yml'

##==meta
protected_robots:
    controller: ProtectedBundle:Meta:robots
    path: /robots.{_format}
    defaults: {_format: 'html'}
