protected_test:
    path: /test/{path}
    defaults: {_controller: ProtectedBundle:Default:test, path: null}
    requirements:
        path: .*

##==meta
protected_robots:
    path: /robots.{_format}
    defaults: {_controller: ProtectedBundle:Meta:robots, _format: 'html'}
