protected_test:
    controller: ProtectedBundle:Default:test
    path: /test/{path}
    defaults: {path: null}
    requirements:
        path: .*

##==meta
protected_robots:
    controller: ProtectedBundle:Meta:robots
    path: /robots.{_format}
    defaults: {_format: 'html'}
