imports:
 - {resource: parameters.yml}
 - {resource: security.yml}
 - {resource: services.yml}
 - {resource: '@TJMBaseBundle/Resources/config/config.yml'}

parameters:
 locale: en
 twig.extension.assets.class: TJM\Bundle\BaseBundle\Extension\AssetsExtension

framework:
 default_locale: '%locale%'
 http_method_override: true
 request:
  formats:
   # md: 'text/x-markdown'
   md: 'text/plain'
   xhtml: 'application/xhtml+xml'
 router:
  resource: '%kernel.root_dir%/config/routing.yml'
  strict_requirements: ~
 secret: '%secret%'
 templating: {engines: ['twig']} #assets_version: SomeVersionScheme
 trusted_hosts: ~

sensio_framework_extra:
 router:
  annotations: false

tjm_base:
 page_wraps:
  full: ":skeletons:full.{format}.twig"
  public_full: 'PublicBundle:skeletons:full.{format}.twig'
  protected_full: 'ProtectedBundle:skeletons:full.{format}.twig'

twig:
 debug: "%kernel.debug%"
 exception_controller: PublicBundle:Meta:exception
 strict_variables: "%kernel.debug%"
