##==protected
#-# first because otherwise local dev setup wasn't matching (ie host as 'local')
_protected_pre:
 defaults:
  request_host: '%protected.host%'
 host: '{request_host}'
 resource: "@ProtectedBundle/Resources/config/routing.pre.yml"
 requirements:
  request_host: '%protected.host.test%'
_protected_post:
 defaults:
  request_host: '%protected.host%'
 host: '{request_host}'
 resource: "@ProtectedBundle/Resources/config/routing.post.yml"
 requirements:
  request_host: '%protected.host.test%'
#--base for outputting generic URLs
protected_base:
 defaults:
  url: null
 host: '%protected.host%'
 path: /{url}
 requirements:
  url: .*
 schemes: [https,http]


##==public
_public_pre:
 defaults:
  request_host: '%public.host%'
 host: '{request_host}'
 resource: "@PublicBundle/Resources/config/routing.pre.yml"
 requirements:
  request_host: '%public.host.test%'
_TJMBase:
 resource: "@TJMBaseBundle/Resources/config/routingBase.yml"
_public_post:
 defaults:
  request_host: '%public.host%'
 host: '{request_host}'
 resource: "@PublicBundle/Resources/config/routing.post.yml"
 requirements:
  request_host: '%public.host.test%'
#--base for outputting generic URLs
public_base:
 defaults:
  url: null
 host: '%public.host%'
 path: /{url}
 requirements:
  url: .*
 schemes: [https,http]
