services:
 _defaults:
  autowire: true
 htmlToMarkdown:
  class: TJM\HtmlToMarkdown\HtmlConverter
  arguments: [{'hard_break': true, 'strip_tags': true}]
  public: true
 markdownToHtml:
  class: ParsedownExtra
  public: true
 ##==controllers
 ProtectedBundle\Controller\:
   resource: '%kernel.project_dir%/src/ProtectedBundle/Controller'
   tags: ['controller.service_arguments']
 PublicBundle\Controller\:
   resource: '%kernel.project_dir%/src/PublicBundle/Controller'
   tags: ['controller.service_arguments']
 ##==listeners
 app.headers_listener:
  class: TJM\TMCom\Listener\HeadersListener
  arguments: ['%kernel.environment%']
  tags:
   - {name: kernel.event_listener, event: kernel.response, priority: -129} #-# priority to prevent CSP stripping by https://github.com/symfony/symfony/pull/25532
