imports:
 - {resource: config.yml}

#==Monolog
#-!! missing deprecations for unknown reason
monolog:
 handlers:
  main_wrap:
   action_level: notice
   excluded_http_codes: [401, 403, 404]
   handler: main
   type: fingers_crossed
  main:
   level: notice
   type:  error_log
  #-! for deprecations
  info:
   level: info
   type: error_log
   channels: [php]
  console:
   type: console
