services:
 _defaults:
  autowire: true
 htmlToMarkdown:
  class: TJM\HtmlToMarkdown\HtmlConverter
  arguments: [{'hard_break': true, 'strip_tags': true}]
  public: true
 markdownToHtml:
  class: ParsedownExtra
  public: true
 TJM\FileStore\FileStore:
   class: TJM\FileStore\FileStore
   arguments: ['%kernel.project_dir%/app/data/data-store/files']
   public: true
 TJM\Pages\Pages:
   class: TJM\Pages\Pages
   arguments: ['%kernel.project_dir%/app/pages', '@TJM\FileStore\FileStore']
   public: true
 TJM\Views\Views:
   arguments: ['@router', '%tjm_base.wraps%']
   public: true
 ##==commands
 PublicBundle\Command\:
   autowire: true
   autoconfigure: true
   resource: '%kernel.project_dir%/src/PublicBundle/Command'
 ##==controllers
 PublicBundle\Controller\:
   resource: '%kernel.project_dir%/src/PublicBundle/Controller'
   tags: ['controller.service_arguments']
 ##==listeners
 app.headers_listener:
  class: PublicBundle\Listener\HeadersListener
  arguments: ['%kernel.environment%']
  tags:
   - {name: kernel.event_listener, event: kernel.response, priority: -129} #-# priority to prevent CSP stripping by https://github.com/symfony/symfony/pull/25532
