imports:
 - {resource: config.yml}

#==FOS HTTP Cache
# fos_http_cache:
#  cache_control:
#   rules:
#    -
#     match:
#      path: ^/
#     headers:
#      reverse_proxy_ttl: 36000

#==Monolog
#-!! missing deprecations for unknown reason
monolog:
 handlers:
  main_wrap:
   action_level: notice
   excluded_http_codes: [401, 403, 404, 418]
   handler: main
   type: fingers_crossed
  main:
   level: notice
   type:  error_log
  console:
   type: console
