services:
 _defaults:
  autowire: true
  bind:
   $env: '%kernel.environment%'
 PublicApp\Service\Assets:
   arguments:
     -
       assetLinks:
         -
           dest: 'fonts'
           src: 'assets/fonts/*'
         -
           dest: 'grunge-pattern.png'
           src: 'assets/grunge-pattern.png'
         -
           dest: 'icomoon'
           src: 'assets/icomoon/*'
         -
           dest: 'icons'
           src: 'assets/icons/*'
         -
           dest: 'images'
           src: 'assets/images/*'
         -
           dest: 'webStuff.jpg'
           src: 'assets/webStuff.jpg'
       distPath: '%assets.dist_path%'
       projectPath: '%kernel.root_dir%'
 TJM\FileStore\FileStore:
   class: TJM\FileStore\FileStore
   arguments: ['%kernel.project_dir%/app/data/data-store/files']
 TJM\HtmlToMarkdown\HtmlConverter:
  arguments: [{'hard_break': true, 'strip_tags': true}]
 TJM\Pages\Pages:
   class: TJM\Pages\Pages
   arguments: ['%kernel.project_dir%/app/pages', '@TJM\FileStore\FileStore']
 ParsedownExtra:
   class: ParsedownExtra #-! required because not namespaced
 TJM\Views\Views:
   arguments: ['@router', '%tjm_base.wraps%', '%public.host%']
   public: true
 ##==commands
 PublicApp\Command\:
   autowire: true
   autoconfigure: true
   resource: '%kernel.project_dir%/src/PublicApp/Command'
 ##==controllers
 PublicApp\Controller\:
   resource: '%kernel.project_dir%/src/PublicApp/Controller'
   tags: ['controller.service_arguments']
 ##==listeners
 app.headers_listener:
  class: PublicApp\Listener\HeadersListener
  arguments: ['%kernel.environment%', '%public.host%']
  tags:
   - {name: kernel.event_listener, event: kernel.response, priority: -129} #-# priority to prevent CSP stripping by https://github.com/symfony/symfony/pull/25532
