public_home:
  path: /
  defaults: {_controller: PublicBundle:Default:simpleFilePage, id: 4}
public_home_default_redirect:
  path: /index.html
  defaults: {_controller: FrameworkBundle:Redirect:urlRedirect, path: /, permanent: true}
public_home_formatted:
  path: /index.{_format}
  defaults: {_controller: PublicBundle:Default:simpleFilePage, id: 4}
public_about_default_redirect:
  path: /about.html
  defaults: {_controller: FrameworkBundle:Redirect:urlRedirect, path: /about, permanent: true}
public_about:
  path: /about.{_format}
  defaults: {_controller: PublicBundle:Default:simpleFilePage, _format: html, id: 5}
public_blog:
  path: /tblog{rest}
  defaults: {_controller: PublicBundle:Default:blog, _format: html, rest: '/'}
  requirements:
    rest: .*
public_web_dev_default_redirect:
  path: /web-dev.html
  defaults: {_controller: FrameworkBundle:Redirect:urlRedirect, path: /web-dev, permanent: true}
public_web_dev:
  path: /web-dev.{_format}
  defaults: {_controller: PublicBundle:Default:simpleFilePage, _format: html, id: 6}


##==meta
public_app_manifest:
  path: /app-manifest.json
  defaults: {_controller: PublicBundle:Meta:appManifest}
public_humans_default_redirect:
  path: /humans.html
  defaults: {_controller: FrameworkBundle:Redirect:urlRedirect, path: /humans, permanent: true}
public_humans:
  path: /humans.{_format}
  defaults: {_controller: PublicBundle:Meta:humans, _format: 'html'}
public_proxy_service_worker:
  path: /_proxy-sw.js
  defaults: {_controller: PublicBundle:Meta:proxyServiceWorker}
public_robots_default_redirect:
  path: /robots.html
  defaults: {_controller: FrameworkBundle:Redirect:urlRedirect, path: /robots, permanent: true}
public_robots:
  path: /robots.{_format}
  defaults: {_controller: PublicBundle:Meta:robots, _format: 'html'}
