public_home:
  controller: PublicBundle:Default:simpleFilePage
  path: /
  defaults: {id: 4}
public_home_default_redirect:
  controller: FrameworkBundle:Redirect:urlRedirect
  path: /index{dotformat}
  defaults:
    path: /
    permanent: true
  requirements:
    dotformat: (\.html|\.php)?
public_home_formatted:
  controller: PublicBundle:Default:simpleFilePage
  path: /index.{_format}
  defaults: {id: 4}
public_about_default_redirect:
  controller: FrameworkBundle:Redirect:urlRedirect
  path: /about.html
  defaults: {path: /about, permanent: true}
public_about:
  controller: PublicBundle:Default:simpleFilePage
  path: /about.{_format}
  defaults: {_format: html, id: 5}
public_blog:
  controller: PublicBundle:Default:blog
  path: /tblog{rest}
  defaults: {_format: html, rest: '/'}
  requirements:
    rest: .*
public_web_dev_default_redirect:
  controller: FrameworkBundle:Redirect:urlRedirect
  path: /web-dev.html
  defaults: {path: /web-dev, permanent: true}
public_web_dev:
  controller: PublicBundle:Default:simpleFilePage
  path: /web-dev.{_format}
  defaults: {_format: html, id: 6}


##==meta
public_app_manifest:
  controller: PublicBundle:Meta:appManifest
  path: /app-manifest.json
public_error_418:
  controller: PublicBundle:Meta:showException
  path: /418
  defaults: {code: 418}
public_error_coffee:
  controller: PublicBundle:Meta:showException
  path: /coffee
  defaults: {code: 418}
public_humans_default_redirect:
  controller: FrameworkBundle:Redirect:urlRedirect
  path: /humans.html
  defaults: {path: /humans, permanent: true}
public_humans:
  controller: PublicBundle:Meta:humans
  path: /humans.{_format}
  defaults: {_format: 'html'}
public_proxy_service_worker:
  controller: PublicBundle:Meta:proxyServiceWorker
  path: /_proxy-sw.js
public_robots_default_redirect:
  controller: FrameworkBundle:Redirect:urlRedirect
  path: /robots.html
  defaults: {path: /robots, permanent: true}
public_robots:
  controller: PublicBundle:Meta:robots
  path: /robots.{_format}
  defaults: {_format: 'html'}

##--seo
public_bing_verification:
  controller: PublicBundle:Meta:bingVerification
  path: '/BingSiteAuth.xml'
public_google_verification:
  controller: PublicBundle:Meta:googleVerification
  path: '/%public.google-verification%'
