public_home:
  controller: PublicBundle:Default:page
  path: /
  defaults: {id: index}
public_home_default_redirect:
  controller: FrameworkBundle:Redirect:urlRedirect
  path: /index{dotformat}
  defaults:
    path: /
    permanent: true
  requirements:
    dotformat: (\.html|\.php)?
public_home_formatted:
  controller: PublicBundle:Default:page
  path: /index.{_format}
  defaults:
    id: index
public_blog:
  controller: PublicBundle:Default:blog
  path: /tblog{rest}
  defaults: {_format: html, rest: '/'}
  requirements:
    rest: .*


##==meta
public_app_manifest:
  controller: PublicBundle:Meta:appManifest
  path: /app-manifest.json
public_error_418:
  controller: PublicBundle:Meta:showException
  path: /418
  defaults: {code: 418}
public_error_coffee:
  controller: PublicBundle:Meta:showException
  path: /coffee
  defaults: {code: 418}
public_humans_default_redirect:
  controller: FrameworkBundle:Redirect:urlRedirect
  path: /humans.html
  defaults: {path: /humans, permanent: true}
public_humans:
  controller: PublicBundle:Meta:humans
  path: /humans.{_format}
  defaults: {_format: 'html'}
public_proxy_service_worker:
  controller: PublicBundle:Meta:proxyServiceWorker
  path: /_proxy-sw.js
public_robots_default_redirect:
  controller: FrameworkBundle:Redirect:urlRedirect
  path: /robots.html
  defaults: {path: /robots, permanent: true}
public_robots:
  controller: PublicBundle:Meta:robots
  path: /robots.{_format}
  defaults: {_format: 'html'}
public_site_nav:
  controller: PublicBundle:Meta:siteNav
  path: /_site-nav.{_format}
  defaults: {_format: null}

##--seo
public_bing_verification:
  controller: PublicBundle:Meta:bingVerification
  path: '/BingSiteAuth.xml'
public_google_verification:
  controller: PublicBundle:Meta:googleVerification
  path: '/%public.google-verification%'
